<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
		<NoWarn>$(NoWarn);NU1507</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
		<PackageVersion Include="Microsoft.AspNetCore.SpaProxy" Version="10.0.4" />
		<PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.4" />
		<PackageVersion Include="Microsoft.OpenApi" Version="2.11.0" />
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
		<PackageVersion Include="xunit" Version="2.9.3" />
		<PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
	</ItemGroup>
</Project>
